#!/bin/bash
FOREGROUND=$(xrdb -query | grep 'color6:'| awk 'NR==1{print $NF}')

ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -font "Monoisome 16" -m 0 -fullscreen 0 -theme-str "*{accent: $FOREGROUND;}")



apps=runapps
sodo=sudorun
file=documents
another=$(echo "$apps
$sodo
$file" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "search: ")

if [ "$another" == "$file" ] ; then
	exec ~/.config/rofi/menu/locate

elif [ "$another" == "$apps" ] ; then
	rofi "${ROFI_OPTIONS[@]}" -modi 'run,drun' -show drun -show-icons

elif [ "$another" == "$sodo" ] ; then
	SUDO_ASKPASS=/home/bresilla/.sbin/askpass rofi "${ROFI_OPTIONS[@]}" -modi 'run,drun' -show drun -theme-str "*{accent: #e53714;}" -run-command 'sudo -A {cmd}'

elif [ -z "$another" ] ; then
	echo "variable empty"

else
  exec nohup $another > /dev/null 2>&1 &
fi
